services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=${VM_NAME}
      - ZBX_SERVER_HOST=${ZABBIX_DN}
      - ZBX_SERVER_ACTIVE=${ZABBIX_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    privileged: true
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge
