services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/etc/host_hostname:ro
    environment:
      - ZBX_HOSTNAME_ITEM=vfs.file.contents[/etc/host_hostname]
      - ZBX_SERVER_HOST=${ZABBIX_DN}
      - ZBX_SERVER_ACTIVE=${ZABBIX_IP}
      - ZBX_HOSTMETADATA=${ZABBIX_PASS}
    ports:
      - target: 10050
        published: 10050
        protocol: tcp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

